services:
  php:
    image: php:8.2-apache
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge